/**
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * @date Mon Sep 28 2015 14:10:49 GMT+0800 (CST)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
(function () {
    var FIELDS = function (model) {
        return [
            {
                "field": "plan_id",
                "title": "计划ID",
                "content": function (item, index) {
                    return item.plan_id ? '<a data-cmd="step_plan" data-plan="' + item.plan_id + '" data-name="'
                                          + item.name + '">' + item.plan_id + '</a>' : '-';
                },
                "sortable": 1
            },
            {
                "field": "name",
                "title": "计划名称",
                "content": function (item, index) {
                    return item.plan_id ? '<a data-cmd="step_plan" data-plan="' + item.plan_id + '" data-name="'
                                          + item.name + '">' + item.name + '</a>' : item.name;
                },
                "sortable": 1
            },
            {
                "field": "impression",
                "title": "展现数",
                "content": mf.getFieldContentLess('impression'),
                "sortable": 1,
                "align": "right"
            },
            {
                "field": "click",
                "title": "点击数",
                "content": mf.getFieldContentLess('click'),
                "sortable": 1,
                "align": "right"
            },
            {
                "field": "cost",
                "title": "消费",
                "content": mf.getFieldContentMoney('cost'),
                "sortable": 1,
                "align": "right"
            },
            {
                "field": "ctr",
                "title": "点击率",
                "content": mf.getFieldContentPercent('ctr'),
                "sortable": 1,
                "align": "right"
            },
            {
                "field": "cpm",
                "title": "千次展现消费",
                "content": mf.getFieldContentMoney('cpm'),
                "sortable": 1,
                "align": "right"
            }
        ];
    };
    mf.index.report.model.dayPlan = new er.Model({
        QUERY_MAP: {},
        LOADER_LIST: ['modelLoader'],
        modelLoader: new er.Model.Loader(function () {
            console.log('modelLoader');
            var loader = this;

            loader.stop();
            mf.parallelAjax([
                {
                    url: '/config',
                    cache: true
                },
                {
                    url: '/plan'
                },
                {
                    url: '/report/cost/' + loader.get('date').replace(/\-/g, '') + '-'
                         + loader.get('date').replace(/\-/g,
                        ''),
                    errorMessage: '分计划单日数据获取失败，请重试。'
                },
                {
                    url: '/report/bill/' + loader.get('date').replace(/\-/g, '') + '-'
                         + loader.get('date').replace(/\-/g,
                        ''),
                    errorMessage: '分日汇总数据获取失败，请重试。'
                }
            ], function (config, plans, reportData, reportBills) {

                loader.set('config', config);
                var reportBillList = reportBills.reduce(function (memory, dayData) {
                    if (!memory[dayData.date]) {
                        memory[dayData.date] = {};
                    }
                    var dateItem = memory[dayData.date][dayData.plan];
                    if (!dateItem) {
                        dateItem = memory[dayData.date][dayData.plan] = {
                            impression: 0,
                            cost: 0,
                            click: 0
                        };
                    }
                    dateItem.impression = dateItem.impression + dayData.impression;
                    dateItem.cost = dateItem.cost + dayData.fee;
                    dateItem.click = dateItem.click + dayData.click;
                    return memory;
                }, {});
                var reportMap = {};
                for (var date in reportData) {
                    var reportBill = reportBillList[date] || {};
                    reportData[date].forEach(function (data) {
                        var item = reportMap[data.plan_id] = reportMap[data.plan_id] || {
                                plan_id: data.plan_id,
                                date: date,
                                list: []
                            };
                        var planBill = reportBill[data.plan_id] || {};
                        item.impression = (item.impression || 0) + data.impression;
                        //item.cost = (item.cost || 0) + data.cost;
                        item.cost = (item.cost || 0) + (planBill.cost || 0);
                        item.click = (item.click || 0) + data.click;
                        item.list.push(data);
                    });
                }
                var reportList = $.map(reportMap, function (n) {
                    n.cost = n.cost || 0;
                    n.click = n.click || 0;
                    n.impression = n.impression || 0;
                    n.cost /= 1000;
                    n.ctr = (n.impression ? n.click / n.impression : 0 ) * 100;
                    n.cpm = (n.impression ? n.cost / n.impression : 0) * 1000;
                    var r = mf.m.utils.deepSearch(plans, n.plan_id, 'id');
                    n.name = r ? r.name : '未知';
                    return n;
                });
                var orderBy = 'cost';
                reportList.sort(function (a, b) {
                    return a[orderBy] > b[orderBy] ? -1 : 1;
                });

                loader.set('order', 'desc');
                loader.set('orderBy', orderBy);
                loader.set('lists', reportList);
                loader.set('plans', plans);
                loader.set('fields', FIELDS(loader));

                loader.start();
            });
        })
    });
})();