/**
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * @date Sat Jun 13 2015 10:52:52 GMT+0800 (CST)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
(function () {
    mf.ud.report = new er.Module({
        config: {
            'action': mf.ud.reportActions
        }
    });
    mf.ud.reportBind = function (action, element) {
        var reportArea = $(
            element,
            typeof action.view.target === 'string'
                ? '#' + action.view.target
                : action.view.target
        );
        var getReportArea = function (id) {
            return $('<div/>', {id: 'area' + id}).appendTo(reportArea).get(0);
        };
        return function (reports, queryMap) {
            var loadReport = arguments.callee;
            action.subAction = action.subAction || {};
            $.each(action.subAction, function (name, sub) {
                if (sub) {
                    sub.leave();
                    action.subAction[name] = null;
                }
            });
            reportArea.children().remove();
            $.each(reports, function (reportPlace, report) {
                console.log('loadReport', reportPlace, report);
                action.subAction[reportPlace] = er.controller.loadSub(
                    getReportArea(reportPlace),
                    'mf.ud.report.' + report.action,
                    {
                        queryMap: report.queryMap || queryMap || {}
                    }
                );
                if (action.subAction[reportPlace]) {
                    action.subAction[reportPlace].onreport = loadReport;
                }
            });
        };
    };
})();