/**
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * @date Tue Sep 08 2015 15:49:07 GMT+0800 (CST)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
(function () {
    var FIELDS = function (model) {
        var needFieldLists = [
            {
                title:'相关媒体',
                align: 'left',
                content: function (item) {
                    return item.media_id ? item.media_name + '(' + item.media_id + ')' : '-';
                }
            },
            {
                title:'相关渠道',
                align: 'left',
                content: function (item) {
                    return item.channel_id ? item.channel_name + '(' + item.channel_id + ')' : '-';
                }
            },
            {
                title:'调整金额',
                stable:1,
                width: 120,
                align: 'center',
                content: mf.getFieldContentMoney('discount')
            },
            {
                title:'备注',
                content: 'comment'
            }
        ];
        return needFieldLists;
    };
    mf.index.account.model.discountList = new er.Model({
        QUERY_MAP: {},
        LOADER_LIST: ['modelLoader'],
        modelLoader: new er.Model.Loader(function () {
            console.log('modelLoader');
            var loader = this;
            loader.set('fields', FIELDS());
            // TODO Generated by er-sync
            // loader.stop();
            // mf.get(
            //    'index/account/discountList?' + loader.getQueryString(),
            //    function (model) {
            //       mf.initModel({loader: loader, model: model, fields: FIELDS});
            //       loader.start();
            //    }
            // );
        })
    });
})();