/**
 * @file Generated by er-sync
 * @author Luics<xukai01@baidu.com>
 * @date Wed Mar 18 2015 14:40:37 GMT+0800 (CST)
 * Copyright (c) 2012 Baidu.com, Inc. All Rights Reserved
 */
(function () {
    var FIELDS = function (model, config) {
        var lists = config.lists.sitePositionList;
        var operateData = mf.operateDataInConfigField(lists);
        var listFieldInConfig = mf.mockFieldInConfig(lists);
        var needFieldLists = {
            'id': {
                /*content: function (item, index) {
                 return '<a data-cmd="edit" data-index="' + index + '">' + operateData.get(item, 'id', '') + '</a>'
                 }*/
            },
            'media': {},
            'modifyTime': {},
            'name': {
                //breakLine: 1
                /*content: function (item, index) {
                 return '<a data-cmd="edit" data-index="' + index + '">' + operateData.get(item, 'name', '') + '</a>'
                 }*/
            },
            'type': {
                datasource: config.maps.sitePositionTypeMap,
                content: function (item) {
                    var r = mf.m.utils.deepSearch('children', config.maps.sitePositionTypeMap,
                        operateData.get(item, 'type'), 'value', 0);
                    return r ? r.name || '-' : '-';
                }
            },
            'displayType': {
                datasource: config.maps.sitePositionDisplayTypeMap,
                content: function (item, index, col, textClass) {
                    if (operateData.get(item, 'type') !== config.maps.sitePositionTypeMap[1].value) {
                        var r = mf.m.utils.deepSearch('children', config.maps.sitePositionDisplayTypeMap,
                            operateData.get(item, 'displayType'), 'value', 0);
                        return r ? r.name || '-' : '-';
                    } else {
                        textClass.push('ui-table-cell-editor-disabled');
                        return '-';
                    }
                }
            },
            'position': {
                datasource: config.maps.displayPositionMap,
                content: function (item, index, col, textClass) {
                    if (operateData.get(item, 'displayType') == config.maps.sitePositionDisplayTypeMap[1].value
                        && operateData.get(item, 'type') != config.maps.sitePositionTypeMap[1].value) {
                        var r = mf.m.utils.deepSearch('children', config.maps.displayPositionMap,
                            operateData.get(item, 'position'), 'value', 0);
                        return r ? r.name || '-' : '-';
                    } else {
                        textClass.push('ui-table-cell-editor-disabled');
                        return '-';
                    }
                }
            },
            'hasCloseBtn': {
                datasource: config.maps.judgeMap,
                content: function (item) {
                    var r = mf.m.utils.deepSearch('children', config.maps.judgeMap,
                        operateData.get(item, 'hasCloseBtn'), 'value', 0);
                    return r ? r.name || '-' : '-';
                }
            },
            'height': {
                title: function () {
                    return '高度(px)' +
                           '<div ui="type:Tip;title:说明;content:-1 表示全屏;skin:help;arrow:tl;"></div>'
                },
                content: function (item) {
                    return operateData.get(item, 'height') || 0;
                },
                validator: function (value, item) {
                    var type = mf.m.utils.deepSearch('children', config.maps.sitePositionTypeMap,
                        operateData.get(item, 'type'), 'value', 0);
                    if (value == -1) {
                        // －1 表示全屏
                        return '';
                    }
                    var heightRange = type.heightRange;
                    if (value < heightRange[0] || value > heightRange[1]) {
                        return '值不在范围内，请修改。（范围：' + heightRange[0] + ' ~ ' + heightRange[1] + '）';
                    }
                }
            },
            'autoPlayInterval': {
                content: function (item) {
                    return operateData.get(item, 'autoPlayInterval') || 0;
                },
                validator: function (value, item) {
                    return operateData.get(item, 'autoPlayInterval') && value < 1 && '不能小于0';
                }
            },
            'operation': {
                title: '操作',
                content: function (item, index) {
                    var ops = [];
                    if (item._isModify) {
                        ops.unshift('<a data-cmd="save" data-index="' + index + '">保存</a>');
                    }
                    /* else if (!item._isNew) {
                     ops.unshift('<a data-cmd="edit" data-index="' + index + '">修改</a>');
                     }*/
                    if (item._isNew) {
                        ops.unshift('<a data-cmd="delete_add" data-index="' + index + '">撤销新增</a>');
                    } else {
                        ops.unshift('<a data-cmd="copy" data-index="' + index + '">复制</a>');
                    }
                    return ops.join('&nbsp;');
                }
            }
        };
        return mf.mockTableFields(needFieldLists, lists);
    };
    mf.index.media.model.sitePosition = new er.Model({
        QUERY_MAP: {
            media: 'siteId'
        },
        LOADER_LIST: ['modelLoader'],
        modelLoader: new er.Model.Loader(function () {
            console.log('modelLoader');
            var loader = this;

            loader.stop();
            mf.parallelAjax([
                {
                    url: '/config',
                    cache: true
                },
                '/adslot' + '?' + loader.getQueryString()
            ], function (config, entities) {
                mf.initEntities({
                    loader: loader,
                    entities: entities,
                    fields: FIELDS(entities, config)
                });
                loader.set('config', config);
                loader.set('sitePositionList', config.lists.sitePositionList);
                loader.set('sitePositionCount', entities.length);
                loader.start();
            });
        })
    });
})();