/**
 * @file Generated by er-sync
 * @author Luics<xukai01@baidu.com>
 * @date Tue Apr 14 2015 14:15:42 GMT+0800 (CST)
 * Copyright (c) 2012 Baidu.com, Inc. All Rights Reserved
 */
(function () {
    /*var getCustomLayout = function (scaleOption) {
        var from = scaleOption.from;
        var to = scaleOption.to;
        var width = scaleOption.width;
        var data = {
            'btnArea': 'left:' + (from / width * 100) + '%; width: ' + ((to - from) / width) * 100 + '%;'
        };
        if (to - from < 1) {
            data.btnArea = 'display: none;'
        }
        return data;
    };*/

    var scaleConfig = {
        width: baseWidth,
        text: {},
        marker: function (value, position) {
            if (position == "right") {
                value = '止' + value + 'px';
            } else {
                value = '按钮起' + value + 'px';
            }
            return value;
        },
        from: baseWidth - 32,
        to: baseWidth,
        template: 'custom_image'
    };

    /*function getContentConfig(data) {
        var configs = {};
        configs.imageArea = {
            text: '图片区域',
            name: 'imageAreaStyle',
            properties: [
                propertyConfig.backgroundColor,
                propertyConfig.transform,
                propertyConfig.animation
            ]
        };
        configs.btnArea = {
            text: '按钮区域',
            name: 'btnAreaStyle',
            properties: [
                propertyConfig.textAlign,
                propertyConfig.backgroundColor,
                propertyConfig.transform,
                propertyConfig.animation
            ]
        };
        configs.btn = {
            text: '按钮',
            name: 'btnContentStyle',
            properties: [
                propertyConfig.content,
                propertyConfig.font,
                propertyConfig.backgroundColor,
                propertyConfig.transform
            ]
        };
        configs = baidu.object.clone(configs);
        configs.btnArea.properties[3].children[0].value = 3;
        return new PropertyConfig(configs, data);
    }*/

    mf.index.media.templateBannerImage = new er.Action({
        model: mf.index.media.model.templateBannerImage,
        view: new er.View({
            template: 'mf_index_media_templateBannerImage',
            UI_PROP: {}
        }),
        STATE_MAP: {},

        onentercomplete: function () {
            console.log('onentercomplete');
            var action = this;
            var model = action.model;

            var config = model.get('config');
            var templateID = model.get('template');
            var styleName = model.get('styleName');

            var refreshActionNewESUI = mf.m.utils.nextTickWrapper(function () {
                $.extend(action._controlMap, esui.init(this));
            });
            var templateData = model.get('templateData') || {};

            if (templateData.scale) {
                scaleConfig.from = templateData.scale.from || 0;
                scaleConfig.to = templateData.scale.to || 0;
            }

            var property = propertyList[styleName](propertyConfig);
            var getCustomLayout = layoutList[styleName];

            var customTemplate = initCustomEditor({
                templateID: templateID,
                styleName: styleName,
                scaleConfig: scaleConfig,
                contentConfig: new PropertyConfig(property, templateData.content),
                getCustomLayout: getCustomLayout,
                refreshESUI: refreshActionNewESUI,
                mockData: new MockData(mf.index.media.model.mockData_image)
            });
            customTemplate.preview();

            var saveBtn = esui.get('saveStyle_' + templateID + '_' + styleName);
            action.save = function () {
                return customTemplate.toJSON();
            };
            saveBtn.onclick = function () {
                console.log('save');
                var result = customTemplate.toJSON();
                var getData = customTemplate.contentConfig.getData();
                mf.m.utils.writeInNewWindow(result);
                mf.m.utils.writeInNewWindow(getData);
            };
            var closeStyle = esui.get('closeStyle_' + templateID + '_' + styleName);
            closeStyle.onclick = function () {
                console.log('close');
            };
            refreshActionNewESUI.call(document.getElementById(action.view.target));
        },
        onleave: function () {
            console.log('onleave');
        }
    });
})();