/**
 * !!Please don't modify this file!!
 *
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
 mf.index.adminActions = [{"path":"/admin/editContent","action":"mf.index.admin.editContent","authority":"LOGIN&SYSTEM","noAuthLocation":"/index/login"},{"path":"/admin/database","action":"mf.index.admin.database","authority":"LOGIN&SYSTEM","noAuthLocation":"/index/login"}];