/**
 * @file Generated by er-sync
 * @author Luics<xukai01@baidu.com>
 * @date Mon Sep 22 2014 10:36:40 GMT+0800 (中国标准时间)
 * Copyright (c) 2012 Baidu.com, Inc. All Rights Reserved
 */
(function () {  
   mf.index.index = new er.Module({
    config:{
      'action': mf.index.indexActions
    }
  });
})();