/**
 * !!Please don't modify this file!!
 *
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
 mf.index.userActions = [{"path":"/user/listApplication","action":"mf.index.user.listApplication","authority":"LOGIN","noAuthLocation":"/index/login"}];