/**
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * @date Mon Sep 28 2015 12:09:08 GMT+0800 (CST)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
(function () {
    var FIELDS = function (model) {
        return [
            {
                "field": "os_id",
                "title": "操作系统名称",
                "content": function (item, index) {
                    return item.name;/*item.os_id === 0 || item.os_id ? '<a data-cmd="step_os" data-os="' + item.os_id + '" data-name="'
                                        + item.name + '">' + item.name + '</a>' : item.name;*/
                    //return '<a data-cmd="media" data-media="' + item.media + '">' + item.name + '</a>'
                },
                "sortable": 1
            },
            {
                "field": "impression",
                "title": "展现数",
                "content": mf.getFieldContentLess('impression'),
                "sortable": 1,
                "align": "right"
            },
            {
                "field": "click",
                "title": "点击数",
                "content": mf.getFieldContentLess('click'),
                "sortable": 1,
                "align": "right"
            },
            /*{
                "field": "cost",
                "title": "消费",
                "content": mf.getFieldContentMoney('cost'),
                "sortable": 1,
                "align": "right"
            },*/
            {
                "field": "ctr",
                "title": "点击率",
                "content": mf.getFieldContentPercent('ctr'),
                "sortable": 1,
                "align": "right"
            }/*,
            {
                "field": "cpm",
                "title": "千次展现消费",
                "content": mf.getFieldContentMoney('cpm'),
                "sortable": 1,
                "align": "right"
            }*/
        ];
    };
    mf.index.report.model.dayOS = new er.Model({
        QUERY_MAP: {},
        LOADER_LIST: ['modelLoader'],
        modelLoader: new er.Model.Loader(function () {
            console.log('modelLoader');
            var loader = this;

            loader.stop();
            mf.parallelAjax([
                {
                    url: '/config',
                    cache: true
                },
                {
                    url: '/report/cost/os/' + loader.get('date').replace(/\-/g, '') + '-' + loader.get('date').replace(/\-/g,
                        ''),
                    errorMessage: '分操作系统单日数据获取失败，请重试。'
                }
            ], function (config, reportData) {

                loader.set('config', config);
                var reportMap = {};
                var allList = [];
                for (var date in reportData) {
                    allList = reportData[date];
                }
                ['plan', 'unit', 'idea'].forEach(function (key) {
                    var value = loader.get(key);
                    if (value) {
                        allList = allList.filter(function (n) {
                            return n[ key+ '_id'] == value;
                        });
                    }
                });
                allList.forEach(function (data) {
                    var item = reportMap[data.os_id] = reportMap[data.os_id] || {
                            os_id: data.os_id,
                            date: date,
                            list: []
                        };
                    item.impression = (item.impression || 0) + data.impression;
                    item.cost = (item.cost || 0) + data.cost;
                    item.click = (item.click || 0) + data.click;
                    item.list.push(data);
                });
                var reportList = $.map(reportMap, function (n) {
                    n.cost = n.cost || 0;
                    n.click = n.click || 0;
                    n.impression = n.impression || 0;
                    n.cost /= 1000;
                    n.ctr = (n.impression ? n.click / n.impression : 0 )* 100;
                    n.cpm = (n.impression ? n.cost / n.impression : 0) * 1000;
                    var r = mf.m.utils.deepSearch(config.maps.osReportTypeMap, n.os_id, 'value');
                    n.name = r ? r.name : '未知';
                    return n;
                });
                var orderBy = 'os_id';
                reportList.sort(function (a, b) {
                    return a[orderBy] > b[orderBy] ? -1 : 1;
                });

                loader.set('order', 'desc');
                loader.set('orderBy', orderBy);
                loader.set('lists', reportList);
                loader.set('fields', FIELDS(loader));

                loader.start();
            });
        })
    });
})();