/**
 * !!Please don't modify this file!!
 *
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
 mf.admin.accountActions = [{"path":"/account/userList","action":"mf.admin.account.userList","authority":"LOGIN","noAuthLocation":"/index/login"}];