/**
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * @date Tue Mar 31 2015 10:59:06 GMT+0800 (CST)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
(function () {
    mf.ud.report.dayPositions = new er.Action({
        model: mf.ud.report.model.dayPositions,
        view: new er.View({
            template: 'mf_ud_report_dayPositions',
            UI_PROP: {
                dayPositionsDate: {
                    range: mf.ud.reportRange
                }
            }
        }),
        STATE_MAP: {
            'date': mf.getDateString(mf.getDate(-1))
        },

        onenter: function () {
            console.log('onenter');
            mf.onenter();
        },
        onafterrepaint: function () {
            console.log('onafterrepaint');
        },
        onafterrender: function () {
            console.log('onafterrender');
            var action = this;
            var model = action.model;

            var date = esui.get('dayPositionsDate');
            date.onchange = mf.m.utils.nextTickWrapper(function (value) {
                console.log('date change', value);
                mf.subActionRefresh(action, {
                    valueAsDate: value,
                    date: mf.getDateString(value)
                });
            }, date);

            var dayPositionsListTable = esui.get('dayPositionsList');
            dayPositionsListTable.onsort = mf.m.utils.nextTickWrapper(function (orderField, order) {
                var orderBy = orderField.field;
                order = order == 'asc' ? 1 : -1;
                dayPositionsListTable.datasource.sort(function (a, b) {
                    return a[orderBy] > b[orderBy] ? order : -order;
                });
                dayPositionsListTable.render();
            }, dayPositionsListTable);
        },
        onentercomplete: function () {
            console.log('onentercomplete');
            mf.loaded();
            var action = this;
            var model = action.model;
            var $element = $('#dayPositionsChart');
            mf.m.highchart_drill(
                '#dayPositionsChart',
                model.get('lists'), model.get('date'),
                function (event) {
                    if (event.point.adslot) {
                        $element.attr({
                            'data-cmd': 'step_adslot',
                            'data-adslot': event.point.adslot,
                            'data-name': event.point.name
                        });
                        $element.trigger('click');
                        $element.attr({
                            'data-cmd': null,
                            'data-adslot': null,
                            'data-name': null
                        });
                    }
                }
            );
        },
        onleave: function () {
            console.log('onleave');
        }
    });
})();