/**
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * @date Tue May 19 2015 19:37:10 GMT+0800 (CST)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
(function () {
    var FIELDS = function (model, config) {
        var lists = config.lists.userList;
        var operateData = mf.operateDataInConfigField(lists);
        var needFieldLists = {
            'id': {},
            'username': {},
            'display': {},
            'operation': {
                title: '操作',
                stable:1,
                width: 80,
                content: function (item, index) {
                    var ops = [];
                    ops.unshift('<a data-cmd="login" data-index="' + index + '">模拟登录</a>');
                    return ops.join('&nbsp;');
                }
            }
        };
        return mf.mockTableFields(needFieldLists, lists);
    };
    mf.admin.account.model.userList = new er.Model({
        QUERY_MAP: {},
        LOADER_LIST: ['modelLoader'],
        modelLoader: new er.Model.Loader(function () {
            console.log('modelLoader');
            var loader = this;

            loader.stop();
            mf.parallelAjax([
                {
                    url: '/config',
                    cache: true
                },
                {
                    url: '/alluser',
                    cache: true
                },
                {
                    url: '/admin/media',
                    cache: true
                },
                {
                    url: '/admin/adslot',
                    cache: true
                }
            ], function (config, entities, medias, adslots) {
                mf.initEntities({
                    loader: loader,
                    entities: entities,
                    fields: FIELDS(entities, config)
                });
                loader.set('config', config);
                loader.set('userList', config.lists.userList);
                loader.set('userCount', entities.length);
                loader.set('medias', medias);
                loader.set('adslots', adslots);
                loader.start();
            });
        })
    });
})();