/**
 * @file Generated by er-sync, module
 * @author killeryyl<longgeyang@jesgoo.com>
 * @date Mon Nov 25 2013 15:54:20 GMT+0800 (中国标准时间)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 * 有不错兼容性的旋转函数
 * shortcut mf.m.rotate
 */
(function(exports, module) {
    var rotate = (function() {
        if (baidu.ie) {
            return function(dom, angle) {
                var rad = angle * (Math.PI / 180);
                var m11 = Math.cos(rad);
                var m12 = -1 * Math.sin(rad);
                var m21 = Math.sin(rad);
                if (baidu.ie < 9) {
                    dom.style.filter = 'progid:DXImageTransform.Microsoft.'
                        + 'Matrix(M11=' + m11 + ',M12=' + m12 + ',M21=' + m21
                        + ',M22=' + m11 + ',SizingMethod="auto expand")';
                } else {
                    var deg = 'rotate(' + angle + 'deg)';
                    dom.style.msTransform = deg;
                    dom.style.transform = deg;
                }
            };
        } else {
            return function(dom, angle) {
                var style = dom.style;
                var css = ['transform', 'MozTransform',
                    'webkitTransform', 'OTransform', 'msTransform'];
                for (var i = 0; i < css.length; ++i) if (css[i] in style) {
                    dom.style[css[i]] = 'rotate(' + angle + 'deg)';
                    break;
                }
            };
        }
    })();

    /**
     * 绑定/销毁旋转事件的各个事件
     * @param {HtmlElement} img
     */
    var bind = function(img) {
        var container = baidu.dom.g('popImg');
        if (!container) {
            container = document.createElement('div');
            container.id = 'popImg';
            container.style.position = 'absolute';
            document.body.appendChild(container);
        }
        var pos = baidu.dom.getPosition(img);
        
        function dispose() {
            var innerImg = $(container).find('img')[0];
            if (innerImg) {
                innerImg.onload = null;
                innerImg.onclick = null;
                innerImg.onmouseout = null;
            }
            container.innerHTML = '';
        }
        
        img.onmouseover = function() {
            dispose();
            container.style.left = pos.left + 'px';
            container.style.top = pos.top + 'px';
            container.innerHTML = '<img angle=0 src="' + img.src + '" />';
            var innerImg = $(container).find('img')[0];
            var offWid = 0;
            
            innerImg.onload = function() {
                offWid = innerImg.offsetWidth;
                innerImg.style.cursor = 'pointer';
            };
            innerImg.onclick = function(e) {
                e = e || event;
                var ang = baidu.dom.getAttr(innerImg, 'angle');
                ang = ((e.clientX > pos.left + offWid / 2 ? 90 : 270)
                    + parseInt(ang, 10)) % 360;
                baidu.dom.setAttr(innerImg, 'angle', ang);
                rotate(innerImg, ang);
            };
            innerImg.onmouseout = dispose;
        };
    };
    exports.rotate = bind;
})(mf && mf.m || exports || {}, mf || module);