/**
 * !!Please don't modify this file!!
 *
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
 mf.index.accountActions = [{"path":"/account/index","action":"mf.index.account.index","authority":"LOGIN&VALID","noAuthLocation":"/account/info"},{"path":"/account/info","action":"mf.index.account.info","authority":"LOGIN","noAuthLocation":"/index/login"}];