/**
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * @date Tue Mar 17 2015 09:45:32 GMT+0800 (CST)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
(function () {  
   mf.index.index = new er.Module({
    config:{
      'action': mf.index.indexActions.concat(
          {"path": "\/", "action": "mf.index.report.index"}
      )
    }
  });
})();