/**
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * @date Tue May 12 2015 15:58:00 GMT+0800 (CST)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
(function () {  
   mf.test.main = new er.Module({
    config:{
      'action': mf.test.mainActions.concat(
          {"path": "\/", "action": "mf.test.main.index"}
      )
    }
  });
})();