/**
 * !!Please don't modify this file!!
 *
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
 mf.monitor.analyzeActions = [{"path":"/analyze/clickArea","action":"mf.monitor.analyze.clickArea"}];