/**
 * @file Generated by er-sync
 * @author Luics<xukai01@baidu.com>
 * @date Mon Sep 22 2014 10:36:40 GMT+0800 (中国标准时间)
 * Copyright (c) 2012 Baidu.com, Inc. All Rights Reserved
 */
(function () {
    mf.index.user.listApplication = new er.Action({
        model: mf.index.user.model.listApplication,
        view: new er.View({
            template: 'mf_index_user_listApplication',
            UI_PROP: {
                pager: {
                    startNumber: 1
                },
                list: {
                    select: 'multi'
                }
            }
        }),
        STATE_MAP: {
            page: 1,
            pageSize: mf.PAGER_MODEL.pageSize
        },

        onenter: function () {
            console.log('onenter');
            mf.onenter();
        },
        onafterrender: function () {
            console.log('onafterrender');
            var action = this;
            var model = action.model;
            mf.initList({action: action});
            mf.initSearch({action: action});
        },
        onentercomplete: function () {
            console.log('onentercomplete');
            var action = this;
            var model = action.model;
            
            var statusTypes = model.get('statusTypes');

            var operationBtn = [
                {
                    id: 'execDelete',
                    op: 'DELETE',
                    before: function (datas, ids, next) {
                        esui.Dialog.confirm({
                            title: '操作确认',
                            content: '你确认删除所选数据么？',
                            onok: function () {
                                next(ids);
                            }
                        });
                    },
                    after: function (datas, successIds) {
                        $.each(successIds, function (i, n) {
                            var valueIndex = mf.m.utils.indexOfArray(datas, n, 'id');
                            if (valueIndex > -1) {
                                datas.splice(valueIndex, 1);
                            }
                        });
                    }
                },
                {
                    id: 'setStatus',
                    op: 'SET_STATUS',
                    after: function (datas, successIds) {
                        var statusValue = esui.get('setStatus').value;
                        console.log(statusValue);
                        $.each(successIds, function (i, n) {
                            var valueIndex = mf.m.utils.indexOfArray(datas, n, 'id');
                            if (valueIndex > -1) {
                                datas[valueIndex]['status'] = +statusValue;
                            }
                        });
                    }
                }
            ];

            var operator = mf.m.uiOperateButton({
                operationBtn: operationBtn,
                url: 'index/user/operateApplication?id={0}'
            });
           
            mf.m.uiFilterSelect({
                status: {
                    data: model.get('statusTypes'),
                    ui: ['filterStatus'],
                    value: ['status']
                },
                keyType: {
                    data: model.get('keyTypes'),
                    ui: ['keyType'],
                    value: ['keyType'],
                    noAllChoice: true
                }
            }, model);
            
            var $list = $('.list-apply');
            $list.off('click').on('click', '[data-cmd]', function () {
                var $this = $(this);
                var cmd = $this.data('cmd');
                var index = $this.data('index');
                if (cmd === 'delete') {
                    operator.trigger('execDelete', index)
                } else {
                    var value = cmd.match(/\d+$/)[0];
                    var valueIndex = mf.m.utils.indexOfArray(statusTypes, value, 'value');
                    operator.trigger('setStatus', index, valueIndex);
                }
            });
            
            esui.get('exportList').onclick = function () {
                window.open('/admin.asp?u=index/user/exportApplication&' + model.getQueryString())
            };
        }
    });
})();