/**
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * @date Tue Apr 14 2015 14:15:42 GMT+0800 (CST)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
(function () {
    var reports= {
        dailyMedia: {
            action: 'dailyMedia'
        },
/*
        hourlyMedia: {
            action: 'hourlyMedia'
        },
*/
        dailyPositions: {
            action: 'dailyPositions'
        },
        dayPositions: {
            action: 'dayPositions'
        }/*,
        hourlyPositions: {
            action: 'hourlyPositions'
        }*/
    };
    mf.index.report.media = new er.Action({
        model: mf.index.report.model.media,
        view: new er.View({
            template: 'mf_index_report_media',
            UI_PROP: {}
        }),
        STATE_MAP: {},

        onenter: function () {
            console.log('onenter');
            mf.onenter();
        },
        onafterrepaint: function () {
            console.log('onafterrepaint');
        },
        onafterrender: function () {
            console.log('onafterrender');
            var action = this;
            var model = action.model;
            var mediaId = model.get('media');
            var reporter = mf.index.reportBind(action, '#mediaReportArea');
            reporter(reports, {
                media: mediaId
            });
            model.set(
                'commands',
                mf.clickCommand.register(
                    [
                        {
                            cmd: 'step_adslot',
                            handle: function (options) {
                                options.adslot && window.open('#/report/position~media=' + mediaId + '&name=' + options.name+ '&adslot=' + options.adslot);
                            }
                        }
                    ],
                    {
                        region: typeof action.view.target === 'string'
                            ? '#' + action.view.target
                            : action.view.target,
                        rewrite: true
                    }
                )
            );
        },
        onentercomplete: function () {
            console.log('onentercomplete');
            mf.loaded();
            var action = this;
            var model = action.model;
        },
        onleave: function () {
            console.log('onleave');
            var action = this;
            $.each(action.subAction || {}, function (name, subAction) {
                subAction && subAction.leave();
            });
            action.subAction = null;
            var commands = action.model.get('commands');
            commands && mf.clickCommand.dispose(commands);
        }
    });
})();