/**
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * @date Wed Nov 25 2015 16:52:52 GMT+0800 (CST)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
(function () {
    mf.index.account.index = new er.Action({
        model: mf.index.account.model.index,
        view: new er.View({
            template: 'mf_index_account_index',
            UI_PROP: {}
        }),
        STATE_MAP: {},

        onenter: function () {
            console.log('onenter');
            mf.onenter();
        },
        onafterrepaint: function () {
            console.log('onafterrepaint');
        },
        onafterrender: function () {
            console.log('onafterrender');
        },
        onentercomplete: function () {
            console.log('onentercomplete');
            mf.loaded();
            var action = this;
            var reportLoader = mf.index.reportBind(action, '#reportArea');
            reportLoader({
                dailyTotal: {
                    action: 'dailyTotal'
                }
            });
            esui.get('newPlan').onclick = mf.m.utils.nextTickWrapper(function () {
                er.locator.redirect('/market/plan~addNew=1');
            });
            esui.get('newIdea').onclick = mf.m.utils.nextTickWrapper(function () {
                er.locator.redirect('/market/idea~addNew=1');
            });
        },
        onleave: function () {
            console.log('onleave');
        }
    });
})();