/**
 * !!Please don't modify this file!!
 *
 * @file Generated by er-sync
 * @author Luics<xukai01@baidu.com>
 * Copyright (c) 2012 Baidu.com, Inc. All Rights Reserved
 */
 mf.index.mediaActions = [{"path":"/media/site","action":"mf.index.media.site","authority":"LOGIN","noAuthLocation":"/index/login"},{"path":"/media/sitePosition","action":"mf.index.media.sitePosition","authority":"LOGIN","noAuthLocation":"/index/login"},{"path":"/media/app","action":"mf.index.media.app","authority":"LOGIN","noAuthLocation":"/index/login"},{"path":"/media/appPosition","action":"mf.index.media.appPosition","authority":"LOGIN","noAuthLocation":"/index/login"},{"path":"/media/siteTemplate","action":"mf.index.media.siteTemplate","authority":"LOGIN","noAuthLocation":"/index/login"},{"path":"/media/templateBannerTextIcon","action":"mf.index.media.templateBannerTextIcon","authority":"LOGIN","noAuthLocation":"/index/login"},{"path":"/media/templateBannerImage","action":"mf.index.media.templateBannerImage","authority":"LOGIN","noAuthLocation":"/index/login"},{"path":"/media/templateBannerFree","action":"mf.index.media.templateBannerFree","authority":"LOGIN","noAuthLocation":"/index/login"}];