/**
 * @file Generated by er-sync, module
 * @author Luics<xukai01@baidu.com>
 * @date Thu Feb 20 2014 16:54:02 GMT+0800 (中国标准时间)
 * Copyright (c) 2012 Baidu.com, Inc. All Rights Reserved
 * shortcut mf.m.ui
 */
(function (exports, module) {

    var runTime;

    var refreshTab = function (process) {
        var tabs = {
            LONG_LEND: false,
            SHORT_LEND: false,
            PRODUCT: false,
            MATERIAL: false,
            LINE: false,
            PURCHASE: false,
            AUCTION: false,
            AD: false,
            FINANCE: false,
            TYPING: false
        };
        /**
         * 每个季度/年度的经营进度
         * 0 等待经营开始
         * 1 当年未开始 填写报表         投放广告 付所得税 付长贷本息
         * 2 参加订货会 自己年度规划       当年开始
         * 3 年度规划 融资长贷
         * 4 当年开始       付短贷本息
         * 5 当季开始 融资短贷      付款入库原料和产品
         * 6 组织生产 下原料订单 租买厂房 生产线 生产原料 转产 * 竞拍会    收取应收款
         * 7 交单研发 订单交货 厂房处理，研发        结束本季度
         * 8 当季结束 扣管理费、扣租金、扣违约金     若不最后一季则回到 2
         * 9 当年结束 扣维修费、折旧、计算本能报表       若不是最后一年则回到 1
         * 10 经营结束
         * 11 破产
         */
        switch (process) {
            case 1: //当年未开始
                tabs.TYPING = true;
                tabs.FINANCE = true;
                tabs.MARKET = true;
                tabs.AD = true;
                break;
            case 2: //参加订货会
                tabs.MARKET = true;
                tabs.PURCHASE = true;
                tabs.AUCTION = true;
                break;
            case 3: //准备当年开始
                tabs.LONG_LEND = true;
                break;
            case 4: //当年开始
                break;
            case 5: //当季开始
                tabs.SHORT_LEND = true;
                break;
            case 6: //组织生产
                tabs.PRODUCT = true;
                tabs.MATERIAL = true;
                tabs.LINE = true;
                break;
            case 7: //交单研发
                break;
            case 8: //当季结束
                break;
            case 9: //当年结束
                break;
            default : //等待开始
        }
        er.permission.init(tabs);
        mf.updateNav1.__called = 0;
        mf.onenter();
        mf.loaded();
        return tabs;
    };

    var refreshCashView = function (process) {
        var cash = runTime.finance.calcProcessCash();
        var cashView = $('.main-info .cash');
        cashView.html(cash);
        if (cash < 0) {
            cashView.addClass('warning');
        }
        else {
            cashView.removeClass('warning');
        }
    };
    var refreshView = function (process) {
        refreshTab(process);
        var viewControl = {
            year: $('.main-info .year'),
            quarter: $('.main-info .quarter')
        };
        $.each(viewControl, function (i, n) {
            n.html(runTime.utils.dataGet(i));
        });
        refreshCashView(process);
        var $btn = $('#processView');
        if ($btn.length) {
            $btn.html(runTime.process.getProcessAction(process).caption);
        }
    };

    var nextProcess = function (cb) {
        //TODO test
        //next();
        //return true;
        //TODO 这里可以做个流程执行的清单供参看
        esui.Dialog.confirm({
            title: '操作确认',
            content: mf.f('<div class="ad-unit-title">确定执行{0}？</div>',
                runTime.process.getProcessAction(runTime.data.process).caption),
            onok: next
        });
        function next() {
            var okTip = runTime.process.getProcessAction(runTime.data.process).tip;
            runTime.process.march({
                onerror: function (err) {
                    mf.formErrorHandler({formError: {'操作失败': err}});
                },
                onok: function () {
                    //cb && cb();
                    //return true;//TODO test
                    if (okTip) {
                        esui.Dialog.alert({
                            title: '操作成功',
                            content: '<div class="ad-unit">'
                                + mf.f('<div class="ad-unit-item">' +
                                '<div class="ad-unit-item-field">#{$item}</div></div>', [].concat(okTip))
                                + '</div>',
                            onok: cb
                        });
                    }
                    else {
                        cb && cb();
                    }
                }
            });
        }
    };

    var dispose = function () {
        runTime = null;
    };

    var ui = function (opt) {
        opt = opt || {};
        runTime = opt.source || {};
        this.refreshCashView = refreshCashView;
        this.refreshView = refreshView;
        this.nextProcess = nextProcess;
        this.dispose = dispose;
    };
    exports.ui = ui;
})(mf && mf.m || exports || {}, mf || module);