/**
 * @file Generated by er-sync, module
 * @author Luics<xukai01@baidu.com>
 * @date Wed Apr 01 2015 15:20:58 GMT+0800 (CST)
 * Copyright (c) 2012 Baidu.com, Inc. All Rights Reserved
 * shortcut mf.m.highchart_overview
 */
(function (exports, module) {
    var emptyData = {
        "click": 0,
        "cpm": 0,
        "ctr": 0,
        "fr": 1,
        "impression": 0,
        "income": 0,
        "request": 0,
        "served_request": 0
    };

    var highchart_overview = function (element, lists, dateRegion) {
        var dateLength = (dateRegion.end - dateRegion.begin) / 24 / 3600000 + 1;
        lists = [].concat(lists);
        if (lists.length < 1) return;
        lists.sort(function (a, b) {
            return a['date'] > b['date'] ? 1 : -1;
        });
        $.each(new Array(dateLength), function (index) {
            var current = mf.getDateString(mf.getDate(index, dateRegion.begin), 'yyyy-MM-dd');
            if (mf.m.utils.indexOfArray(lists, current, 'date') === -1) {
                lists.splice(index, 0, $.extend({}, emptyData, {date: current}));
            }
        });
        console.log('chart original', lists, dateLength, dateRegion.begin);
        var cData = {};
        $.each(lists, function (index, item) {
            $.each(item, function (key, value) {
                cData[key] || (cData[key] = []);
                cData[key].push(value);
            });
        });
        cData.ctr = $.map(cData.ctr || [], function (value) {
            return value * 100;
        });
        $(element).highcharts({
            chart: {
                spacingTop: 60,
                marginTop: 60
            },
            title: {
                text: null
            },
            colors: [
                "#1c62b8",
                "#f6505c",
                "#f6c928",
                "#19b2b7",
                "#8772cd",
                "#eb6f25"
            ],
            credits: {
                enabled: false
            },
            exporting: {
                enabled: false
            },
            tooltip: {
                shared: true,
                crosshairs: {
                    width: 2,
                    color: 'gray',
                    dashStyle: 'shortdot'
                }
            },
            legend: {
                align: 'right',
                verticalAlign: 'top',
                itemMarginTop: -40,
                floating: true,
                itemStyle: {
                    fontWeight: 'normal',
                    color: '#777',
                    fontSize: 12,
                    symbolPadding: 10
                },
                itemDistance: 20
            },
            plotOptions: {
                line: {
                    marker: {
                        symbol: 'circle',
                        radius: 2
                    },
                    lineWidth: 1
                },
                spline: {
                    marker: {
                        enabled: false
                    }
                }
            },
            xAxis: [
                {
                    categories: cData.date,
                    lineColor: '#e5e5e5',
                    tickColor: '#e5e5e5',
                    labels: {
                        style: {
                            color: '#7a7a7a'
                        },
                        rotation: -45,
                        align: 'right'
                    },
                    tickPosition: 'inside',
                    tickLength: 4,
                    tickmarkPlacement: 'on'
                }
            ],
            yAxis: [
                { // Primary yAxis
                    min: 0,
                    gridLineWidth: 0,
                    title: {
                        text: null
                    },
                    labels: {
                        align: 'left',
                        formatter: function () {
                            return this.value + '次';
                        },
                        enabled: true
                    },
                    opposite: true
                }, { // Secondary yAxis
                    min: 0,
                    gridLineWidth: 0,
                    title: {
                        text: null
                    },
                    labels: {
                        formatter: function () {
                            return this.value + '次';
                        },
                        enabled: false
                    }

                }, { // Tertiary yAxis
                    min: 0,
                    lineWidth: 5,
                    gridLineWidth: 1,
                    gridLineColor: '#e5e5e5',
                    title: {
                        text: null
                    },
                    labels: {
                        formatter: function () {
                            return '¥' + this.value;
                        },
                        enabled: true
                    }
                }, { // 4th yAxis
                    min: 0,
                    gridLineWidth: 0,
                    title: {
                        text: null
                    },
                    labels: {
                        enabled: false
                    }
                }, { // 5th yAxis
                    gridLineWidth: 0,
                    title: {
                        text: null
                    },
                    min: 0,
                    labels: {
                        enabled: false
                    }
                }
            ],
            series: [
                {
                    name: '总收入',
                    type: 'spline',
                    yAxis: 2,
                    data: cData.income,
                    tooltip: {
                        valueDecimals: 2,
                        valuePrefix: '¥'
                    },
                    marker: {
                        symbol: null
                    },
                    lineWidth: 5,
                    color: '#ff0000'
                }, {
                    name: '展现数',
                    type: 'line',
                    yAxis: 0,
                    data: cData.impression,
                    tooltip: {
                        valueSuffix: ' 次'
                    }

                }, {
                    name: '点击数',
                    type: 'line',
                    yAxis: 1,
                    data: cData.click,
                    tooltip: {
                        valueSuffix: ' 次'
                    }
                }/*, {
                 name: '填充率',
                 type: 'line',
                 data: cData.fr,
                 yAxis: 4,
                 tooltip: {
                 valueSuffix: ' %'
                 },
                 visible: false
                 }*/, {
                    name: '点击率',
                    type: 'line',
                    data: cData.ctr,
                    yAxis: 3,
                    tooltip: {
                        valueDecimals: 2,
                        valueSuffix: '%'
                    },
                    visible: false
                }, {
                    name: '请求数',
                    type: 'line',
                    yAxis: 0,
                    data: cData.request,
                    tooltip: {
                        valueSuffix: ' 次'
                    },
                    visible: false

                }, {
                    name: '每千次展现收入',
                    type: 'line',
                    data: cData.cpm,
                    yAxis: 3,
                    tooltip: {
                        valueDecimals: 2,
                        valuePrefix: '¥'
                    },
                    visible: false
                }
            ]
        });
    };
    exports.highchart_overview = highchart_overview;
})(mf && mf.m || exports || {}, mf || module);