/**
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * @date Sat Jun 13 2015 10:52:52 GMT+0800 (CST)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
(function () {
    var FIELDS = function (model) {
        return [];
    };
    mf.ud.report.model.index = new er.Model({
        QUERY_MAP: {},
        LOADER_LIST: ['modelLoader'],
        modelLoader: new er.Model.Loader(function () {
            console.log('modelLoader');

            var loader = this;
            loader.stop();
            mf.parallelAjax([
                {
                    url: '/config',
                    cache: true
                },
                '/ud/media'
            ], function (config, medias) {
                loader.set('config', config);
                loader.set('siteMediaList', config.lists.siteMediaList);
                loader.set('sitePositionList', config.lists.sitePositionList);
                loader.set('medias', medias);

                loader.start();
            });
        })
    });
})();