/**
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * @date Fri Sep 25 2015 13:42:17 GMT+0800 (CST)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
(function () {
    var reports= {
        dailyIdea: {
            action: 'dailyIdea'
        },
        dayRegion: {
            action: 'dayRegion'
        },
        dayOS: {
            action: 'dayOS'
        }
    };
    mf.index.report.idea = new er.Action({
        model: mf.index.report.model.idea,
        view: new er.View({
            template: 'mf_index_report_idea',
            UI_PROP: {}
        }),
        STATE_MAP: {},

        onenter: function () {
            console.log('onenter');
            mf.onenter();
        },
        onafterrender: function () {
            console.log('onafterrender');
            var action = this;
            var model = action.model;
            var ideaId = model.get('idea');
            var unitId = model.get('unit');
            var reporter = mf.index.reportBind(action, '#ideaReportArea');
            reporter(reports, {
                idea: ideaId,
                unit: unitId
            });
        },
        onleave: function () {
            console.log('onleave');
            var action = this;
            $.each(action.subAction || {}, function (name, subAction) {
                subAction && subAction.leave();
            });
            action.subAction = null;
            var commands = action.model.get('commands');
            commands && mf.clickCommand.dispose(commands);
        }
    });
})();