/**
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * @date Fri Sep 25 2015 13:42:17 GMT+0800 (CST)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
(function () {
    var reports= {
        dailyPlan: {
            action: 'dailyPlan'
        },
        dayUnit: {
            action: 'dayUnit'
        },
        dayRegion: {
            action: 'dayRegion'
        },
        dayOS: {
            action: 'dayOS'
        }
    };
    mf.index.report.plan = new er.Action({
        model: mf.index.report.model.plan,
        view: new er.View({
            template: 'mf_index_report_plan',
            UI_PROP: {}
        }),
        STATE_MAP: {},

        onenter: function () {
            console.log('onenter');
            mf.onenter();
        },
        onafterrender: function () {
            console.log('onafterrender');
            var action = this;
            var model = action.model;
            var planId = model.get('plan');
            var reporter = mf.index.reportBind(action, '#planReportArea');
            reporter(reports, {
                plan: planId
            });
            model.set(
                'commands',
                mf.clickCommand.register(
                    [
                        {
                            cmd: 'step_unit',
                            handle: function (options) {
                                options.unit && window.open('#/report/unit~plan=' + planId + '&name=' + options.name+ '&unit=' + options.unit);
                            }
                        }
                    ],
                    {
                        region: typeof action.view.target === 'string'
                            ? '#' + action.view.target
                            : action.view.target,
                        rewrite: true
                    }
                )
            );
        },
        onentercomplete: function () {
            console.log('onentercomplete');
            mf.loaded();
            var action = this;
            var model = action.model;
        },
        onleave: function () {
            console.log('onleave');
            var action = this;
            $.each(action.subAction || {}, function (name, subAction) {
                subAction && subAction.leave();
            });
            action.subAction = null;
            var commands = action.model.get('commands');
            commands && mf.clickCommand.dispose(commands);
        }
    });
})();