/**
 * @file Generated by er-sync
 * @author Jeffersondyj<dengyijun@baidu.com>
 * @date Tus July 30 2013 13:23:38 GMT+0800 (China Standard Time)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */

/**
 * ma和app公用的相关函数
 */

(function () {
    /**
     * @param {Object} opt
     *   model {Object} 后端回传的data
     *   reflect {Object=} 字段映射规则
     *   keys {Array} 回传data的索引，用来的和dom中的eleId绑定
     * @public
     */
    mf.postError = function (opt) {
        var model = opt.model;
        var leftError = {};
        var keys = opt.keys || [];
        for (var i in model) {
            var index = mf.m.utils.deepSearch(keys, i, 'key');
            var id = index > -1 ? keys[index].dom : i;
            var dom = $('#' + id + 'Error');
            if (dom.length) {
                dom.html(model[i]).show();
                dom[0].scrollIntoView(); //将比较前面的post错误定位显示
            } else {
                leftError[i] = model[i];
            }
        }
        if (!$.isEmptyObject(leftError)) {
            mf.formErrorHandler({
                formError: leftError,
                reflect: opt.reflect
            });
        }
    };
    var commandElement = mf.m.commandElement;
    if (commandElement) {
        mf.clickCommand = commandElement('click');
        /*
         * 全局“展开/收起”命令
         * 命令元素必须包含 data-cmd="toggleExpend" data-target="targetId"
         * 可选参数
         * data-open="展开时文本"
         * data-close="收起时文本"
         * data-method="" 收起展开时对应的方式，visibility | display , 默认 display
         * 元素可选事件 onshow, onhide，事件需预先赋值给targetId元素。
         * 事件返回false时将中断行为
         */
        mf.clickCommand.register(
            {
                cmd: 'toggleExpend',
                handle: function (options) {
                    var target = document.getElementById(options.target);
                    if (!target) {
                        return true;
                    }
                    var ele = this.target;
                    var txtOpen = ele.txtOpen || options.open;
                    var txtClose = ele.txtClose || options.close;
                    var method = options.method || 'display';
                    var onshow = target.onshow;
                    var onhide = target.onhide;
                    if (ele.isOpened) {
                        if (onhide && onhide() === false) {
                            return true;
                        }
                        txtOpen = txtOpen || ele.innerHTML || '收起';
                        ele.isOpened = false;
                        ele.txtOpen = txtOpen;
                        ele.innerHTML = txtClose || '展开';
                        method === 'visibility'
                            ? target.style.visibility = 'hidden'
                            : target.style.display = 'none';
                    } else {
                        if (onshow && onshow() === false) {
                            return true;
                        }
                        txtClose = txtClose || ele.innerHTML || '展开';
                        ele.isOpened = true;
                        ele.txtClose = txtClose;
                        ele.innerHTML = txtOpen || '收起';
                        if (/absolute|fixed/i.test($(target).css('position'))) {
                            target.style.top = ($(ele).offset().top
                                - $(ele.parentNode).offset().top + 26) + 'px';
                        }
                        method === 'visibility'
                            ? target.style.visibility = 'visible'
                            : target.style.display = 'block';
                    }
                }
            }
        );
    }
})();