/**
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * @date Thu Oct 15 2015 15:54:49 GMT+0800 (CST)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
(function () {
    var FIELDS = function (model) {
        return [];
    };
    mf.admin.manage.model.dspID = new er.Model({
        QUERY_MAP: {},
        LOADER_LIST: ['modelLoader'],
        modelLoader: new er.Model.Loader(function () {
            console.log('modelLoader');
            var loader = this;
            loader.set('dspTabs', [
                {
                    title: '用户维度',
                    actionName: 'userDSPID'
                },
                {
                    title: '媒体维度',
                    actionName: 'mediaDSPID'
                },
                {
                    title: '广告位维度',
                    actionName: 'adslotDSPID'
                },
                {
                    title: '域名维度',
                    actionName: 'domainDSPID'
                },
                {
                    title: '百度DSP ID管理',
                    actionName: 'baiduDSP'
                },
                {
                    title: '腾讯DSP ID管理',
                    actionName: 'tencentDSP'
                }
            ]);
        })
    });
})();