/**
 * @file Generated by er-sync
 * @author killeryyl<longgeyang@jesgoo.com>
 * @date Tue Mar 17 2015 09:45:32 GMT+0800 (CST)
 * Copyright (c) 2015 jesgoo.com, Inc. All Rights Reserved
 */
$(function () {
    console.log('er.init union');
    try {
        mf.authority.parse(mf.getUser().authority);
    }
    catch (e) {
    }

    mf.ajaxResponse['/config'] = mf.m.config;
    er.init();
});

mf.union = mf.union || {};

mf.clickCommand = mf.m.commandElement('click');
