/**
 * @file Generated by er-sync
 * @author Luics<xukai01@baidu.com>
 * @date Thu Apr 02 2015 11:19:59 GMT+0800 (CST)
 * Copyright (c) 2012 Baidu.com, Inc. All Rights Reserved
 */
(function () {
    mf.index.report.dailyChannel = new er.Action({
        model: mf.index.report.model.dailyChannel,
        view: new er.View({
            template: 'mf_index_report_dailyChannel',
            UI_PROP: {
                dailyChannelDateRegion: {
                    range: mf.index.reportRange
                }
            }
        }),
        STATE_MAP: {
            'dateRegion':  mf.getDateString(mf.getDate(-7)) + ',' +
                           mf.getDateString(mf.getDate(-1))
        },

        onenter: function () {
            console.log('onenter');
            mf.onenter();
        },
        onafterrepaint: function () {
            console.log('onafterrepaint');
        },
        onafterrender: function () {
            console.log('onafterrender');
            var action = this;
            var model = action.model;
            var dateRegion = esui.get('dailyChannelDateRegion');
            dateRegion.onchange = mf.m.utils.nextTickWrapper(function (value, name, index) {
                console.log('date change', name, index);
                mf.subActionRefresh(action, {
                    dateRegion: dateRegion.getValue()
                });
            }, dateRegion);
            var listTable = esui.get('dailyChannelList');
            listTable.onsort = mf.m.utils.nextTickWrapper(function (orderField, order) {
                var orderBy = orderField.field;
                order = order == 'asc' ? 1 : -1;
                listTable.datasource.sort(function (a, b) {
                    return a[orderBy] > b[orderBy] ? order : -order;
                });
                listTable.render();
            }, listTable);
        },
        onentercomplete: function () {
            console.log('onentercomplete');
            mf.loaded();
            var action = this;
            var model = action.model;
        },
        onleave: function () {
            console.log('onleave');
        }
    });
})();