/**
 * @file Generated by er-sync
 * @author Luics<xukai01@baidu.com>
 * @date Fri Mar 27 2015 15:20:13 GMT+0800 (CST)
 * Copyright (c) 2012 Baidu.com, Inc. All Rights Reserved
 */
(function () {

    mf.index.report.dayMedias = new er.Action({
        model: mf.index.report.model.dayMedias,
        view: new er.View({
            template: 'mf_index_report_dayMedias',
            UI_PROP: {
                dayMediasDate: {
                    range: mf.index.reportRange
                }
            }
        }),
        STATE_MAP: {
            'date': mf.getDateString(mf.getDate(-1))
        },

        onenter: function () {
            console.log('onenter');
        },
        onafterrepaint: function () {
            console.log('onafterrepaint');
        },
        onafterrender: function () {
            console.log('onafterrender');
            var action = this;
            var model = action.model;

            var date = esui.get('dayMediasDate');
            date.onchange = mf.m.utils.nextTickWrapper(function (value) {
                console.log('date change', value);
                mf.subActionRefresh(action, {
                    valueAsDate: value,
                    date: mf.getDateString(value)
                });
            }, date);

            var dayMediasListTable = esui.get('dayMediasList');
            dayMediasListTable.onsort = mf.m.utils.nextTickWrapper(function (orderField, order) {
                var orderBy = orderField.field;
                order = order == 'asc' ? 1 : -1;
                dayMediasListTable.datasource.sort(function (a, b) {
                    return a[orderBy] > b[orderBy] ? order : -order;
                });
                dayMediasListTable.render();
            }, dayMediasListTable);
        },
        onentercomplete: function () {
            console.log('onentercomplete');
            var action = this;
            var model = action.model;
            //mf.m.highchart_drill('#dayMediasChart', model.get('lists'), model.get('date'));
        },
        onleave: function () {
            console.log('onleave');
        }
    });
})();