/**
 * @file Generated by er-sync
 * @author Luics<xukai01@baidu.com>
 * @date Tue Mar 31 2015 10:59:06 GMT+0800 (CST)
 * Copyright (c) 2012 Baidu.com, Inc. All Rights Reserved
 */
(function () {
    mf.index.report.dayPositions = new er.Action({
        model: mf.index.report.model.dayPositions,
        view: new er.View({
            template: 'mf_index_report_dayPositions',
            UI_PROP: {
                dayPositionsDate: {
                    range: mf.index.reportRange
                }
            }
        }),
        STATE_MAP: {
            'date':  mf.getDateString(mf.getDate(-1))
        },

        onenter: function () {
            console.log('onenter');
            mf.onenter();
        },
        onafterrepaint: function () {
            console.log('onafterrepaint');
        },
        onafterrender: function () {
            console.log('onafterrender');
            var action = this;
            var model = action.model;

            var date = esui.get('dayPositionsDate');
            date.onchange = mf.m.utils.nextTickWrapper(function (value) {
                console.log('date change', value);
                mf.subActionRefresh(action, {
                    valueAsDate: value,
                    date: mf.getDateString(value)
                });
            }, date);

            var dayPositionsListTable = esui.get('dayPositionsList');
            dayPositionsListTable.onsort = mf.m.utils.nextTickWrapper(function (orderField, order) {
                var orderBy = orderField.field;
                order = order == 'asc' ? 1 : -1;
                dayPositionsListTable.datasource.sort(function (a, b) {
                    return a[orderBy] > b[orderBy] ? order : -order;
                });
                dayPositionsListTable.render();
            }, dayPositionsListTable);
        },
        onentercomplete: function () {
            console.log('onentercomplete');
            mf.loaded();
            var action = this;
            var model = action.model;
            mf.m.highchart_drill('#dayPositionsChart', model.get('lists'), model.get('date'));
        },
        onleave: function () {
            console.log('onleave');
        }
    });
})();