/**
 * @file Generated by er-sync
 * @author Luics<xukai01@baidu.com>
 * @date Tue Apr 14 2015 14:15:42 GMT+0800 (CST)
 * Copyright (c) 2012 Baidu.com, Inc. All Rights Reserved
 */
(function () {
    var reports = {
        dailyTotal: {
            action: 'dailyTotal'
        },
        dayMedias: {
            action: 'dayMedias'
        },
        dailyMedias: {
            action: 'dailyMedias'
        }/*,
         hourlyMedias: {
         action: 'hourlyTotal'
         }*/
    };
    mf.index.report.total = new er.Action({
        model: mf.index.report.model.total,
        view: new er.View({
            template: 'mf_index_report_total',
            UI_PROP: {}
        }),
        STATE_MAP: {},

        onenter: function () {
            console.log('onenter');
            mf.onenter();
        },
        onafterrepaint: function () {
            console.log('onafterrepaint');
        },
        onafterrender: function () {
            console.log('onafterrender');
            var action = this;
            var model = action.model;
            var reporter = mf.index.reportBind(action, '#totalReportArea');
            reporter(reports);
            model.set(
                'commands',
                mf.clickCommand.register(
                    [
                        {
                            cmd: 'step_media',
                            handle: function (options) {
                                window.open('#/report/media~media=' + options.media + '&name=' + options.name);
                            }
                        }
                    ],
                    {
                        region: typeof action.view.target === 'string'
                            ? '#' + action.view.target
                            : action.view.target,
                        rewrite: true
                    }
                )
            );
        },
        onentercomplete: function () {
            console.log('onentercomplete');
            mf.loaded();
            var action = this;
            var model = action.model;
        },
        onleave: function () {
            console.log('onleave');
            var action = this;
            $.each(action.subAction || {}, function (name, subAction) {
                subAction && subAction.leave();
            });
            action.subAction = null;
            var commands = action.model.get('commands');
            commands && mf.clickCommand.dispose(commands);
        }
    });
})();