/**
 * !!Please don't modify this file!!
 *
 * @file Generated by er-sync
 * @author Luics<xukai01@baidu.com>
 * Copyright (c) 2012 Baidu.com, Inc. All Rights Reserved
 */
 mf.index.indexActions = [{"path":"/index/login","action":"mf.index.index.login"},{"path":"/index/register","action":"mf.index.index.register"}];