/**
 * @file Generated by er-sync
 * @author Luics<xukai01@baidu.com>
 * @date Tue May 26 2015 14:24:38 GMT+0800 (CST)
 * Copyright (c) 2012 Baidu.com, Inc. All Rights Reserved
 */
mf.index.market.model = {};